export const weatherCodeDescriptions = {
    en: {
        0: "Clear sky",
        1: "Mainly clear",
        2: "Partly cloudy",
        3: "Overcast",
        45: "Fog",
        48: "Depositing rime fog",
        51: "Light drizzle",
        53: "Moderate drizzle",
        55: "Dense drizzle",
        61: "Slight rain",
        63: "Moderate rain",
        65: "Heavy rain",
        71: "Slight snowfall",
        73: "Moderate snowfall",
        75: "Heavy snowfall",
        80: "Slight rain showers",
        81: "Moderate rain showers",
        82: "Violent rain showers",
        95: "Thunderstorm",
        96: "Thunderstorm with slight hail",
        99: "Thunderstorm with heavy hail"
    },
    ja: {
        0: "晴天",
        1: "ほぼ晴れ",
        2: "曇りがち",
        3: "曇り",
        45: "霧",
        48: "霧氷の霧",
        51: "小雨",
        53: "適度な霧雨",
        55: "強い霧雨",
        61: "小雨",
        63: "適度な雨",
        65: "強い雨",
        71: "小雪",
        73: "適度な雪",
        75: "強い雪",
        80: "小雨のにわか雨",
        81: "適度なにわか雨",
        82: "激しいにわか雨",
        95: "雷雨",
        96: "小さい雹を伴う雷雨",
        99: "激しい雹を伴う雷雨"
    }
};